#!/usr/bin/env python3
"""
Map Saver Node for TurtleBot3 Lab06
Provides a service to save the current map generated by SLAM
"""

import rclpy
from rclpy.node import Node
from rclpy.executors import MultiThreadedExecutor
from std_srvs.srv import Empty
from nav_msgs.msg import OccupancyGrid
import yaml
import subprocess
import os
from datetime import datetime


class MapSaver(Node):
    def __init__(self):
        super().__init__('map_saver_node')

        self.get_logger().info('Map Saver Node Started')

        # Create service to save map
        self.save_map_service = self.create_service(
            Empty,
            'save_map',
            self.save_map_callback
        )

        # Subscribe to map topic to monitor map updates
        self.map_subscription = self.create_subscription(
            OccupancyGrid,
            '/map',
            self.map_callback,
            10
        )

        self.current_map = None
        self.map_received = False

        self.get_logger().info('Map Saver Node initialized. Call /save_map service to save the current map.')

    def map_callback(self, msg):
        """Callback for receiving map updates from SLAM"""
        self.current_map = msg
        if not self.map_received:
            self.map_received = True
            self.get_logger().info('Map data received. Map updates are being monitored.')

    def save_map_callback(self, request, response):
        """Service callback to save the current map"""
        try:
            if not self.map_received:
                self.get_logger().warn('No map data received yet. Cannot save map.')
                return response

            # Create maps directory if it doesn't exist
            maps_dir = os.path.expanduser('~/maps')
            os.makedirs(maps_dir, exist_ok=True)

            # Generate filename with timestamp
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            map_name = f'turtlebot3_lab06_map_{timestamp}'
            map_path = os.path.join(maps_dir, map_name)

            # Use ros2 run nav2_map_server map_saver_cli to save the map
            cmd = [
                'ros2', 'run', 'nav2_map_server', 'map_saver_cli',
                '-f', map_path,
                '--ros-args', '-p', 'save_map_timeout:=10000'
            ]

            self.get_logger().info(f'Saving map to: {map_path}')
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)

            if result.returncode == 0:
                self.get_logger().info(f'Map saved successfully!')
                self.get_logger().info(f'Map files: {map_path}.pgm and {map_path}.yaml')

                # Also save a summary of the mapping session
                self.save_mapping_summary(map_path, timestamp)

            else:
                self.get_logger().error(f'Failed to save map: {result.stderr}')

        except subprocess.TimeoutExpired:
            self.get_logger().error('Map saving timed out')
        except Exception as e:
            self.get_logger().error(f'Error saving map: {str(e)}')

        return response

    def save_mapping_summary(self, map_path, timestamp):
        """Save a summary file with mapping session information"""
        try:
            summary_data = {
                'mapping_session': {
                    'timestamp': timestamp,
                    'lab': 'TurtleBot3 Lab06 - SLAM',
                    'map_resolution': float(self.current_map.info.resolution) if self.current_map else 'Unknown',
                    'map_width': self.current_map.info.width if self.current_map else 'Unknown',
                    'map_height': self.current_map.info.height if self.current_map else 'Unknown',
                    'origin_x': float(self.current_map.info.origin.position.x) if self.current_map else 'Unknown',
                    'origin_y': float(self.current_map.info.origin.position.y) if self.current_map else 'Unknown',
                    'notes': 'Map created using SLAM Toolbox with TurtleBot3 simulation'
                }
            }

            summary_file = f'{map_path}_summary.yaml'
            with open(summary_file, 'w') as f:
                yaml.dump(summary_data, f, default_flow_style=False)

            self.get_logger().info(f'Mapping summary saved: {summary_file}')

        except Exception as e:
            self.get_logger().warn(f'Could not save mapping summary: {str(e)}')


def main(args=None):
    rclpy.init(args=args)

    map_saver = MapSaver()

    executor = MultiThreadedExecutor()
    executor.add_node(map_saver)

    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        map_saver.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()